# Beschreibt wie unsere CI/CD Pipeline mit der Gitlab-CI funktioniert
#
# Referenz: https://docs.gitlab.com/ce/ci/yaml/

image: emundo/docker-compose-openjdk-node-gradle:latest

stages:
    - install
    - lint-and-compile
    - compile
    - test
    - analysis
    - build
    - deploy
    - dist

cache:
    paths:
        - /home/emundo/.npm

before_script:
    - npm ci

lint:
    image: node:alpine
    stage: lint-and-compile
    script:
        - npm run lint # npm run lint

compile:
    image: node:alpine
    stage: lint-and-compile
    script:
        -  npm run build
    artifacts:
        name: "$CI_PROJECT_PATH_SLUG-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        when: on_success
        paths:
            - dist/htdocs/
        expire_in: 1 week # Wir brauchen das Aritfakt nur bis zum Ende der Pipeline

docker-container:
    stage: build
    services:
      - docker:dind
    variables:
      DOCKER_DRIVER: overlay
      DOCKER_HOST: tcp://localhost:2375
    cache:
        # nur Pullen, wir wollen die gelöschen dev-Dependencies nicht aus dem Cache löschen
        policy: pull
    script:
        - npm run build --prod --aot --minifyjs --minifycss --optimizejs
        # Tag with commit tag or latest if not aviable.
        # Docker-Container bauen (baue immer mit den aktuellsten images)
        - docker-compose build --pull
        # Docker Registry Login um das Pushen von Images zu ermöglichen
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # Docker-Container in die Registry pushen
        - docker-compose push
