version: '2'



services:
  nginx:
    image: registry.schreib.io/tsv-forstenried/handballtag/client/client
    container_name: handballtag-client-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
