version: '2'

services:
  nginx:
    image: registry.schreib.io/tsv-forstenried/client/nginx
    labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    environment:
      - NGINX_PORT=80

