version: '2'

services:
  nginx:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 20000
      unhealthy_threshold: 3
      initializing_timeout: 120000
      reinitializing_timeout: 120000
      strategy: recreate
      request_line: 'GET /'
      healthy_threshold: 2
      response_timeout: 5000
