apiVersion: v1
kind: Service
metadata:
    name: {{.Values.postgres.hostname}}
    labels:
        app: {{.Values.application.name}}
        environment: {{.Values.application.environment}}
spec:
    ports:
        - port: 5432
    selector:
        app: {{.Values.application.name}}-postgres
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{.Values.application.name}}-postgres-volume
    labels:
        app: {{.Values.application.name}}-postgres
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.application.name}}-postgres
    labels:
        app: {{.Values.application.name}}
        environment: {{.Values.application.environment}}
spec:
    selector:
        matchLabels:
            app: {{.Values.application.name}}-postgres
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: {{.Values.application.name}}-postgres
        spec:
            containers:
                - image: postgres:10.5-alpine
                  name: {{.Values.application.name}}-postgres
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                key: password
                                name: postgres-password
                      - name: POSTGRES_DB
                        value: {{.Values.postgres.database}}
                      - name: POSTGRES_USER
                        value: {{.Values.postgres.user}}
                      - name: TZ
                        value: CET
                  ports:
                      - containerPort: 5432
                  volumeMounts:
                      - name: {{.Values.application.name}}-postgres-persistent-storage
                        mountPath: /var/lib/postgres/data
            volumes:
                - name: {{.Values.application.name}}-postgres-persistent-storage
                  persistentVolumeClaim:
                      claimName: {{.Values.application.name}}-postgres-volume
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    labels:
        app: {{.Values.application.name}}
        environment: {{.Values.application.environment}}
type: Opaque
stringData:
    password: {{.Values.postgres.password}}
